version: '2'
services:

  consul:
    build: consul
    ports:
      - 8400:8400
      - 8500:8500
      - 8600:8600
  a-service:
    build: a-service
    ports:
      - 5100:5100

  b-service:
    build: b-service
    ports:
      - 5200:5200

  admin-dashboard:
    build: admin-dashboard
    ports:
      - 7300:7300
