# export SERVICE_USER=admin
# export SERVICE_PASSWORD=admin

export CONFIG_SERVICE_USER=cfg
export CONFIG_SERVICE_PASSWORD=111222

# export A_SERVICE_PASSWORD=111222
# export B_SERVICE_PASSWORD=111222

# export MONGODB_USER=demo
# export MONGODB_PASSWORD=111222
# export MONGODB_DATABASE=demodb
