version: '2'
services:
  kong-database:
    image: postgres:9.4
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
    ports:
    - 5432:5432/tcp
    labels:
      io.rancher.container.pull_image: 'false'
  kong-dashboard:
    image: pgbi/kong-dashboard
    links:
    - kong:kong
    ports:
    - 8100:8080/tcp
    labels:
      io.rancher.container.pull_image: 'false'
  kong:
    image: kong
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
    external_links:
    - apps-spring/lookup:lookup
    - apps-spring/calc:calc
    - apps-spring/config:config
    - apps-node/plus:plus
    dns:
    - 192.169.0.1
    ports:
    - 80:8000/tcp
    - 443:8443/tcp
    - 8001:8001/tcp
    expose:
    - '7946'
    - 7946/udp
    command:
    - /bin/sh
    - -c
    - kong start --vv
    labels:
      io.rancher.container.pull_image: 'false'